# Generated by Django 4.0.4 on 2022-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ourdishes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourdishes',
            name='image',
            field=models.ImageField(upload_to='media.images'),
        ),
    ]
