# Generated by Django 4.0.4 on 2022-05-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ourdishes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='regular', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
