# Generated by Django 4.0.4 on 2022-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_label_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='portions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
