# Generated by Django 4.0.4 on 2022-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_portions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=100)),
                ('portions', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='portions',
        ),
    ]
